server:
  port: 8010

spring:
  application:
    name: mall-user  #微服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.167.161:8848 #配置nacos注册中心地址
        ephemeral: false

#mall-order: # 被调用的微服务名
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule